# Uncomment the following line to enable deep sleep
CONFIG_ZMK_SLEEP=y

# Enable the display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
CONFIG_ZMK_EXT_POWER_START=y
CONFIG_NICE_VIEW_WIDGET_STATUS=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y